services:
  app:
    env_file:
      - path: ./.env
        required: true
    image: norookezi/${PROJECT_NAME}:latest
    ports:
      - "${API_PORT}:${API_PORT}"
    container_name: ${PROJECT_NAME}
    restart: unless-stopped